version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file serverless.yml --s3-bucket sqs-s3-serverless-codebuild --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml